version: "3.6"
services:
  laravel:
    build: 
        context: .
        dockerfile: laravel.dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
        - .:/app
    ports:
        - 8000:8000
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  graphql-engine:
    image: hasura/graphql-engine:v2.23.0
    ports:
      - "8080:8080"
      #- "8888:8888"
    depends_on:
      - "postgres"
      # - "mssql"
    restart: always
    env_file:
      - hasura.env
    environment:
    #   ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
    #   ## this env var can be used to add the above ms sql server database to Hasura as a data source. this can be removed/updated based on your needs
    #   MSSQL_DATABASE_URL: Driver={ODBC Driver 18 for SQL Server};Server=tcp:mssql,1433;Database=tempdb;Uid=sa;Pwd=Password1;Encrypt=optional
    #   ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
    #   ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_AUTH_HOOK: #http://localhost:8000/api/auth/hasura
      HASURA_GRAPHQL_AUTH_HOOK_MODE: POST
      #HASURA_GRAPHQL_JWT_SECRET: "{\"type\": \"HS256\", \"key\": \"FwBoFsLQCEtUwlYLKaM3KxSs2imizhR2PTivHxABMKwXsAczRg8mkLFmuRJVgj4d\"}"
    #   HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      # HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  pg_data:
  # mssql_data:
